### PR TITLE
ContextMenu_ThrowCorpseOffWindow

### PR DESCRIPTION
**Pull request by IvanRios01**
I translated both options to spanish! :D Happy to give you a hand!

### CODE REVIEW

**Comment by quarantin** [comment]
Thanks man! Appreciated :)

**Comment by IvanRios01** [comment]
You are welcome! it was my first time using github so sorry in advance if i
touched something wrong haha 😅

**Comment by quarantin** [comment]
No it was good, no problem. To spare yourself the trouble though, you could have just posted the translation in the comment section of the mod directly. Most people do that :)

**Comment by IvanRios01** [comment]
Well next time yeah im posting in the comment section haha. if you need
help translating something to spanish from your future projects feel free
to contact me!. of course i'm doing it ad honorem so don't worry about
money or anything

**Pull request merged**
